import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header"
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import { getSession } from "next-auth/client";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";

export default function Home({session}) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex">
        <Sidebar />
  <Feed />
  <Widgets />
      </main>
    </div>
  );
}
export async function getServerSideProps(context) {
  // Get User
  const session = await getSession(context);

  

  return {
    props: { session},
  };
}